stages:
  - update-release
  - build
  - push
  
variables:
  DOCKER_REGISTRY: registry.gitlab.com
  DOCKER_IMAGE: $DOCKER_REGISTRY/a_anand_91119/gitlab-arm

update-release:
  stage: update-release
  script:
    - |
      echo "Updating RELEASE file with tag:'$CI_COMMIT_TAG'"
    - sed -i "s/^RELEASE_VERSION=.*/RELEASE_VERSION=${CI_COMMIT_TAG}/" RELEASE
  rules:
    - if: $CI_COMMIT_TAG 

build:
  stage: build
  script:
    - |
      echo "Logging into Docker registry"
    - |
      echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $DOCKER_REGISTRY
    - |
      echo "Building Docker image for ARM architecture"
    - docker build --tag $DOCKER_IMAGE:$CI_COMMIT_TAG .
  rules:
    - if: $CI_COMMIT_TAG
  tags:
    - arm

push:
  stage: push
  script:
    - |
      echo "Logging into Docker registry"
    - | 
      echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $DOCKER_REGISTRY
    - |
      echo "Pushing Docker image to registry"
    - docker push $DOCKER_IMAGE:$CI_COMMIT_TAG
  rules:
    - if: $CI_COMMIT_TAG
  tags:
    - arm
  dependencies:
    - build
