stages:
  - update-release
  - build
  - push
  
variables:
  DOCKER_REGISTRY: registry.gitlab.com
# docker build -t registry.gitlab.com/a_anand_91119/gitlab-arm .
# docker push registry.gitlab.com/a_anand_91119/gitlab-arm
  DOCKER_IMAGE: $DOCKER_REGISTRY/a_anand_91119/gitlab-arm

# This job will run only when a tag is pushed
update-release:
  stage: update-release
  script:
    - echo "Updating RELEASE file with tag: ${CI_COMMIT_TAG}"
    - sed -i "s/^RELEASE_VERSION=.*/RELEASE_VERSION=${CI_COMMIT_TAG}/" RELEASE
    - cat RELEASE  # Just for verification
  rules:
    - if: $CI_COMMIT_TAG  # Run only on tags

# # Job to build Docker image on ARM architecture (Raspberry Pi)
# build:
#   stage: build
#   script:
#     - echo "Logging into Docker registry"
#     - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $DOCKER_REGISTRY
#     - echo "Building Docker image for ARM architecture"
#     - docker build --platform linux/arm64 -t $DOCKER_IMAGE:$CI_COMMIT_TAG .
#   rules:
#     - if: $CI_COMMIT_TAG  # Run only on tags
#   tags:
#     - arm  # Ensure this tag matches the runner's tag for ARM machines

# # Job to push Docker image to registry
# push:
#   stage: push
#   script:
#     - echo "Pushing Docker image to registry"
#     - docker push $DOCKER_IMAGE:$CI_COMMIT_TAG
#   rules:
#     - if: $CI_COMMIT_TAG  # Run only on tags
#   tags:
#     - arm
#   dependencies:
#     - build