stages:
  - update-release
  - build
  - push
  
variables:
  DOCKER_REGISTRY: registry.gitlab.com
  DOCKER_IMAGE: $DOCKER_REGISTRY/a_anand_91119/gitlab-arm
  TEMP_VARIABLE: 16.11.8-ce.0

# update-release:
#   stage: update-release
#   script:
#     - |
#       echo "Updating RELEASE file with tag:'$CI_COMMIT_TAG'"
#     - sed -i "s/^RELEASE_VERSION=.*/RELEASE_VERSION=${TEMP_VARIABLE}/" RELEASE
#     - cat RELEASE
#   rules:
#     - if: $CI_COMMIT_TAG 

build:
  stage: build
  image:
    name: "docker:stable"
  services:
    - name: docker:dind
      alias: buildcontainer
      entrypoint: ["dockerd-entrypoint.sh", "--tls=false"]
  variables:
    DOCKER_HOST: tcp://buildcontainer:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - |
      echo $DOCKER_REGISTRY_PASSWORD | docker login -u $DOCKER_REGISTRY_USER --password-stdin $DOCKER_REGISTRY
  script:
    - |
      echo "Building Docker image for ARM architecture"
      echo "Docker image and tag: '$DOCKER_IMAGE:$CI_COMMIT_TAG'"
    - docker build -t $DOCKER_IMAGE:$CI_COMMIT_TAG .
  # rules:
  #   - if: $CI_COMMIT_TAG
  # tags:
  #   - saas-linux-medium-arm64

push:
  stage: push
  image:
    name: "docker:stable"
  services:
    - name: docker:dind
      alias: buildcontainer
      entrypoint: ["dockerd-entrypoint.sh", "--tls=false"]
  variables:
    DOCKER_HOST: tcp://buildcontainer:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - |
      echo $DOCKER_REGISTRY_PASSWORD | docker login -u $DOCKER_REGISTRY_USER --password-stdin $DOCKER_REGISTRY
  script:
    - |
      echo "Pushing Docker image to registry"
    - docker push $DOCKER_IMAGE:$CI_COMMIT_TAG
  # rules:
  #   - if: $CI_COMMIT_TAG
  # tags:
  #   - saas-linux-medium-arm64
  dependencies:
    - build
